Partie 0 – mise en place de l’environnement

4) Installer et importer seaborn, matplotlib et pandas

In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

5) Importer mesures_capteurs.csv dans le dataframe df

In [3]:
df = pd.read_csv("../data/mesures_capteurs.csv")

6) Explorer le dataframe df

In [4]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [5]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

In [6]:
df.tail(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
595,M0331,2026-01-18 18:00:00,C007,B003,20.72,59.39,1012.82,79.67,OK
596,M0215,2026-01-13 22:00:00,C011,B004,28.01,69.25,997.50,310.00,OK
597,M0467,2026-01-24 10:00:00,C011,B004,27.87,66.57,1011.33,310.53,OK
598,M0122,2026-01-10 01:00:00,C002,B001,23.83,63.30,1006.76,199.36,OK
599,M0021,2026-01-05 20:00:00,C009,B003,24.37,58.38,1010.10,132.82,OK
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB

In [8]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

In [9]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='object')

In [10]:
df.shape

(605, 9)

Partie 1 – Gestion des doublons
Avec Pandas,
1) vérifier l’existence de doublons dans df

In [28]:
duplique = df.duplicated().sum()
print(duplique)
df[df.duplicated()] #les lignes concernées

0

Empty DataFrame
Columns: [id_mesure, date_heure, id_capteur, batiment, temperature, humidite, pression, consommation, etat]
Index: []

2) le cas échéant, supprimer les doublons puis vérifier la suppression

In [29]:
df = df.drop_duplicates()

In [30]:
df.duplicated().sum()

np.int64(0)

Partie 2 – Sélection de y (cible) et X (caractéristiques)
1) Définir "etat" comme la cible ou valeur à prédire et "temperature", "humidite",
"pression" et "consommation" comme caractéristiques ou variables explicatives

In [66]:
df = df.dropna(subset=["etat"])

In [68]:

X = df[["temperature", "humidite", "pression", "consommation"]]   #les caracteristiques
y = df["etat"]   #le cible

2) Afficher les cinq premières lignes de X et de y

In [60]:
print(X.head())

   temperature  humidite  pression  consommation
0        25.46     58.06   1008.95        287.28
1        24.00     79.73    993.39        116.20
2        25.82     54.47   1010.32        288.50
3        28.23     69.39   1019.62        136.65
4        20.58     53.80   1016.58        182.62

In [61]:
print(y.head())

0    OK
1    OK
2    OK
3    OK
4    OK
Name: etat, dtype: object

3) Quel est le type du problème de machine learning ?

C'est un problème de classification supervisée parce qu'on connaît déjà la valeur etat dans les données d'entraînement et on veut apprendre à la prédire à partir de temperature, humidite, pression et consommation.

Partie 3 – Découpage Train/Test
Diviser X en deux ensembles distincts : un pour l'entraînement (train) et un pour le test (test).
Avec les conditions suivantes : 20% des données serviront au test ; garantir la reproductibilité du
découpage ; conserver les mêmes proportions de classes dans l'ensemble de train et de test que
dans les données d'origine.

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2, #20 % des données pour le test et 80 % pour l'entraînement.
    random_state=42, #garantit que le découpage sera toujours le même.
    stratify=y #conserve les mêmes proportions de classes dans y_train et y_test
)

Partie 4 – Gestion des valeurs manquantes
1) Vérifier l’existence de valeurs manquantes

In [72]:
X_test.isna().sum()

temperature     0
humidite        0
pression        0
consommation    0
dtype: int64

2) Sélectionner SimpleImputer avec la médiane